-- MySQL Script generated by MySQL Workbench
-- Fri Mar 25 08:41:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Examen2Parcial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Examen2Parcial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Examen2Parcial` DEFAULT CHARACTER SET utf8 ;
USE `Examen2Parcial` ;

-- -----------------------------------------------------
-- Table `Examen2Parcial`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen2Parcial`.`Usuario` (
  `Codigo` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `TipoUsuario` VARCHAR(15) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2Parcial`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen2Parcial`.`Producto` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) BINARY NULL,
  `Precio` DECIMAL(18,2) NULL,
  `Existencia` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2Parcial`.`Pedido (factura)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen2Parcial`.`Pedido (factura)` (
  `Id` INT NOT NULL,
  `NombreCliente` VARCHAR(45) NULL,
  `Pedido` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
